baseURL = "https://pamasol.github.io/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Pamasol Electrics"
theme = "hugo-theme-relearn"
themesdir = "./themes"
publishdir = "docs"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = true
relativeURLs = true

[params]
  editURL = "https://github.com/pamasol/pamasol.github.io/tree/main/content/"
  description = "Pamasol Electrics bietet Wissen in den Bereichen Maschinenbau, Elektrotechnik und Softwareentwicklung."
  author = "Pamasol"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  titleSeparator = "-"
  themeVariant = "pamasol"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"

[markup.goldmark.renderer]
  unsafe= true

[module]
  [module.hugoVersion]
    min = "0.25"

[Languages]
  [Languages.en]
    title = "Pamasol Electrics Portal"
    weight = 1
    languageName = "English"
    landingPageURL = "/en"
    landingPageName = "<i class='fas fa-home'></i> Home"

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-globe-europe'></i> Pamasol Official Website"
    identifier = "pamasolWebsite"
    url = "https://www.pamasol.com/"
    weight = 10

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-linkedin'></i> Pamasol on LinkedIn"
    identifier = "pamasolLinkedIn"
    url = "https://www.linkedin.com/company/pamasol"
    weight = 20

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Pamasol on GitHub"
    identifier = "pamasolGitHub"
    url = "https://github.com/pamasol/"
    weight = 30

  [Languages.de]
    title = "Pamasol Electrics Portal"
    weight = 1
    languageName = "Deutsch"
    landingPageURL = "/de/"
    landingPageName = "<i class='fas fa-home'></i> Startseite"

  [[Languages.de.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-globe-europe'></i> Offizielle Webseite von Pamasol"
    identifier = "pamasolWebsite"
    url = "https://www.pamasol.com/"
    weight = 10

  [[Languages.de.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-linkedin'></i> Pamasol auf LinkedIn"
    identifier = "pamasolLinkedIn"
    url = "https://www.linkedin.com/company/pamasol"
    weight = 20

  [[Languages.de.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Pamasol auf GitHub"
    identifier = "pamasolGitHub"
    url = "https://github.com/pamasol/"
    weight = 30

